//// Each #kernel tells which function to compile; you can have many kernels
//#pragma kernel CSMain
//
//StructuredBuffer<int> orignalIndices;
//StructuredBuffer<bool> removedIndices;
//StructuredBuffer<int> addedIndices;
//
//int totalIndices;
//int removedIndices;
//
//RWStructuredBuffer<int> newIndices;
//
//[numthreads(5, 1, 1)]
//void RemoveIndices(uint3 id : SV_DispatchThreadID)
//{
//
//}
